version: '3.8'
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend.txt
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:8000

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend.txt
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS=*