version: '3.8'
services:
  kenyare-frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend.txt
    ports:
      - "5173:5173"
    depends_on:
      - kenyare-backend
    environment:
      - VITE_API_BASE_URL=http://139.59.57.31:8000
      - VITE_PROD_PORT=5173
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  kenyare-backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend.txt
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS=139.59.57.31
      - OPENAI_API_KEY=NEED_TO_GET_KEY
    volumes:
      - kenyare-backend-data:/var/lib/kenyare
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - kenyare-frontend
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  kenyare-backend-data: