version: '3.8'
services:
  kenyare-frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend.txt
    ports:
      - "5173:5173"
    depends_on:
      - kenyare-backend
    environment:
      - VITE_API_BASE_URL=http://kenyare-backend:8000

  kenyare-backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend.txt
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS=*