apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kenyare-static-files
  namespace: kenyare
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
